services:
  - type: web
    name: quantity-measurement-react
    env: static
    rootDir: quantity-measurement-react
    buildCommand: npm install && npm run build
    publishDir: dist
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: VITE_API_BASE_URL
        value: https://quantitymeasurementapp-igyb.onrender.com
